source 'https://supermarket.getchef.com'

cookbook 'apt',                 git: 'https://github.com/opscode-cookbooks/apt.git'
cookbook 'chef-sugar',          git: 'https://github.com/sethvargo/chef-sugar.git'
cookbook 'mysql',               git: 'https://github.com/opscode-cookbooks/mysql.git'
cookbook 'php',                 git: 'https://github.com/opscode-cookbooks/php.git'
cookbook 'runit',               git: 'https://github.com/hw-cookbooks/runit.git'
cookbook 'xml',                 git: 'https://github.com/opscode-cookbooks/xml.git'
cookbook 'yum-mysql-community', git: 'https://github.com/opscode-cookbooks/yum-mysql-community.git'
cookbook 'bluepill',            git: 'https://github.com/opscode-cookbooks/bluepill.git'
cookbook 'chef_handler',        git: 'https://github.com/opscode-cookbooks/chef_handler.git'
cookbook 'nginx',               git: 'https://github.com/miketheman/nginx.git'
cookbook 'php-fpm',             git: 'https://github.com/mirceapreotu/cookbook-php-fpm'
cookbook 'windows',             git: 'https://github.com/opscode-cookbooks/windows.git'
cookbook 'yum',                 git: 'https://github.com/opscode-cookbooks/yum.git'
cookbook 'build-essential',     git: 'https://github.com/opscode-cookbooks/build-essential.git'
cookbook 'iis',                 git: 'https://github.com/opscode-cookbooks/iis.git'
cookbook 'ohai',                git: 'https://github.com/opscode-cookbooks/ohai.git'
cookbook 'rsyslog',             git: 'https://github.com/opscode-cookbooks/rsyslog.git'
cookbook 'yum-epel',            git: 'https://github.com/opscode-cookbooks/yum-epel.git'
cookbook 'wordpress',           git: 'https://github.com/mirceapreotu/wordpress-chef-cookbook.git'